### ISSUE TITLE
awsにproduction用の各種リソースを作成する

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast-kanban#26]
- [x] vpc
- [x] s3
- [ ] rds
- [x] eks
- [x] eks-nodes
- [x] elasticache

**Comment by inductor** [comment]
Elasticcacheは入れます？前に高かったので途中でやめたと思いますが

**Comment by takaishi** [comment]
あ、EKS上にRedis立てたんだっけか。いらないと思う

**Comment by jacopen** [comment]
Elasticacheは無しで～
