### ISSUE TITLE
localでの環境開発及び動作確認[oshiro]

### ISSUE THREAD

**Issue by oshiro3** [cloudnativedaysjp/dreamkast-kanban#31]

**Comment by oshiro3** [comment]
とりあえず深く考えずに環境構築して docker-compose up した結果 ui がうまく動いていないっぽい？
* dreamkast repository で動かしている
* database のマイグレーション関係は上手くいっていて seed 通りのデータが入っている
* すべてのコンテナの状態が running 
* ~~環境はWSL2なのでホストが localhost ではない~~ ←これは誤り
![image.png](https://images.zenhubusercontent.com/608f8d1bb8cb9f91c32de851/7c8c48a2-1e54-4ce4-a92b-f231a105d562)

**Comment by inductor** [comment]
WSLはlocalhostでbindしてくれるはずですね

**Comment by oshiro3** [comment]
@inductor 
確かに localhost にバインドされてました！
昔はできなかったので今もできないと思い込んでました。。

**Comment by oshiro3** [comment]
どうも `localhost:3001/api/...` ではなく `lcoalhost:3000/api/...` を叩きにいかないといけないのに 3001 に向かって言っているのが原因なような気がしますが、はたして。。

http://localhost:3000/api/v1/events/cndo2021
![image.png](https://images.zenhubusercontent.com/608f8d1bb8cb9f91c32de851/3eb1b1c3-7fe5-4140-8773-9bb01c4c158e)

**Comment by oshiro3** [comment]
nginx が 8080 で受けているのでそっちにつながないとダメという至極当たり前の話に気づかなかったよう

**Comment by oshiro3** [comment]
docker-compose.yaml をそのままに `RAILS_ENV=production` だと `config.action_cable.allowed_request_origins` がコメントアウトされいるので `Request origin not allowed:` になるので,  `RAILS_ENV=development` にするとエラーを出さなくなる。

若干コンソールにエラーは出ているけど LOGIN していないところに起因する話だと思うので恐らく問題なしかと

その他タイムテーブルやその中身も見れているので一応は問題無く立ち上がっている様子
