### ISSUE TITLE
CFP募集機能

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-kanban#32]
## Background

これまではGoogleFormなどを使ってCFPを実現してきたが、dreamkastでサポートする。
しかし、時間の都合既にTalkモデルを使ってCFPをOpenしてしまっているので、CICDではそれを考慮しつつ実装する。

## Goal

- Proposalモデルの追加
    - TalkモデルとのRelation
    - ProposalのStatus管理
- Proposalの一覧画面(Admin)
- ProposalのStatus更新機能
- ProposalのStatusをSpeakerDashboardに表示する機能
- PropsalのStatusによってタイムテーブルやTalk一覧に表示するかどうかを制御する
- Reject時にどうするかの仕様決め

**Comment by takaishi** [comment]
proposalsテーブルを追加してそこでstatusを管理しようと考えている。悩ましいのはtalkとproposalの関係。
proposalにtalkが従属するのがよさそうではある。
